# 0.12.0-rc2
window:
  decorations: none
  startup_mode: Maximized
  decoration_theme_variant: dark

scrolling:
  history: 10000
  multiplier: 10

font:
  normal:
    family: 'DejaVuSansMono Nerd Font Mono'
  size: 9.0

draw_bold_text_with_bright_colors: true

shell:
  program: /bin/bash

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  unfocused_hollow: true
